apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: cluster-config
spec:
  targetNamespace: cluster-config
  releaseName: nginx
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: cluster-config
      version: "15.12.2"
  interval: 1m
  values:
    # Customize your NGINX deployment here
    replicaCount: 2
    service:
      type: NodePort
