apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: cluster-config
spec:
  targetNamespace: nginx
  releaseName: nginx
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: cluster-config
      version: "15.12.2"
  interval: 1m
